---
output: pdf_document
---
```{r}
raw.clinical.patients <- read.table("data_clinical_patient.txt", sep = "\t", 
                                    header = TRUE)
raw.data.mutations <- read.table("data_mutations.txt", sep = "\t", 
                                 header = TRUE)
raw.data.RNAseq <- read.csv("RNAseq_BRCA.csv", row.names=1)

#Filter data where you only have 0 or 1 read count across all samples.
raw.data.RNAseq <- raw.data.RNAseq[rowSums(raw.data.RNAseq)>1,]
```

```{r message=FALSE}
colnames(raw.data.RNAseq) <- make.unique(sapply(colnames(raw.data.RNAseq), function(name) {
  segments <- strsplit(name, "\\.")[[1]]
  paste(segments[1:3], collapse = "-")
}))
```

```{r}
#Unique Patients in each data set 
unique.clinical <- as.data.frame(unique(raw.clinical.patients$PATIENT_ID))
unique.mutations <- as.data.frame(unique
                                  (raw.data.mutations$Tumor_Sample_Barcode))
unique.RNA <- as.data.frame(colnames(raw.data.RNAseq[,1:length(raw.data.RNAseq)]))

#Addition patient ID's to Mutation data 
mutation.patients <- as.data.frame(raw.data.mutations$Tumor_Sample_Barcode)
colnames(mutation.patients) <- "Patient_ID"
mutation.patients$Patient_ID <- substr(mutation.patients$Patient_ID, 1, 12)
raw.data.mutations <- cbind(mutation.patients, raw.data.mutations)

colnames(unique.clinical) <- "Patient_ID"
colnames(unique.mutations) <- "Patient_ID"
colnames(unique.RNA) <- "Patient_ID"
unique.mutations$Patient_ID <- substr(unique.mutations$Patient_ID, 1, 12)

#Finding common patients
common_patient_ids <- Reduce(intersect, list(
  unique.clinical$Patient_ID,
  unique.mutations$Patient_ID,
  unique.RNA$Patient_ID
))

#3 data sets with all 975 common patients
clinical.data <- raw.clinical.patients[raw.clinical.patients$PATIENT_ID 
                                        %in% common_patient_ids, ]
mutation.data <- raw.data.mutations[raw.data.mutations$Patient_ID 
                                    %in% common_patient_ids, ]
seq.data <- raw.data.RNAseq[,names(raw.data.RNAseq)
                            %in% clinical.data$PATIENT_ID]
```

```{r, message=FALSE, warning=FALSE}
data <- clinical.data

library(dplyr)

data[data == "" | data == " "] <- NA

data <- data %>%
  mutate(
    RACE = ifelse(is.na(RACE) | RACE == "American Indian or Alaska Native", "Native", RACE),
    RACE = ifelse(is.na(RACE) | RACE == "Black or African American", "Black or AA", RACE))
```

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(gridExtra)

# Plot 1: Pie plot for Sex
data_counts_sex <- data.frame(table(data$SEX))
colnames(data_counts_sex) <- c("SEX", "Count")
data_counts_sex$Percentage <- round((data_counts_sex$Count / sum(data_counts_sex$Count)) * 100, 1)

p1 <- ggplot(data_counts_sex, aes(x = "", y = Count, fill = SEX)) +
  geom_bar(stat = "identity", width = 1) +  
  coord_polar(theta = "y") +
  labs(title = "Distribution of Sex", fill = "Sex", size = 22) +
  theme_void() +  # Remove gridlines and axes
  theme(plot.title = element_text(size = 20)) + 
  geom_text(aes(label = paste(Count, "(", Percentage, "%)", sep = "")), 
            position = position_stack(vjust = 0.5)) 

# Plot 2: Pie plot for Race
data_counts_race <- data.frame(table(data$RACE))
colnames(data_counts_race) <- c("RACE", "Count")
data_counts_race$Percentage <- round((data_counts_race$Count / sum(data_counts_race$Count)) * 100, 1)

p2 <- ggplot(data_counts_race, aes(x = "", y = Count, fill = RACE)) +
  geom_bar(stat = "identity", width = 1) +  # Create bars (used for pie chart)
  coord_polar(theta = "y") +  # Convert to pie chart
  labs(title = "Distribution of Race", fill = "Race", size = 22) +
  theme_void() +  # Remove gridlines and axes
  theme(plot.title = element_text(size = 20)) + 
  geom_text(aes(label = ifelse(RACE %in% "White", 
                               paste(Count, "(", Percentage, "%)", sep = ""),
                               "")), 
            position = position_stack(vjust = 0.5))

# Plot 3: Bar plot for SUBTYPE
p3 <- ggplot(data, aes(x = SUBTYPE)) +
  geom_bar(fill = "lightcoral") +
  labs(title = "Cancer Subtypes", x = "Subtype", y = "Count", size = 22) +
  theme_minimal()+
  theme(plot.title = element_text(size = 20)) + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

# Plot 4: Histogram for AGE
p4 <- ggplot(data, aes(x = AGE)) +
  geom_histogram(binwidth = 5, fill = "lightgray", color = "black") +
  geom_vline(aes(xintercept = mean(data$AGE)), color = "red", size = 1) +  # Mean line
  geom_text(aes(x = 37, y = 130, label = paste("mean: ", round(mean(data$AGE), 2)), size = 8), 
            color = "red", vjust = -0.5) +  # Add text for the mean
  labs(title = "Distribution of Age", x = "Age", y = "Frequency", size = 22) +
  theme_minimal()+
theme(plot.title = element_text(size = 20)) 

# Plot 5: Barplot for Genetic Ancestry
p5 <- ggplot(data, aes(x = GENETIC_ANCESTRY_LABEL)) +
  geom_bar(fill = "magenta") +
  labs(title = "Genetic Ancestry", x = "Genetic Ancestry", y = "Count", size = 20) +
  theme_minimal()+
  theme(plot.title = element_text(size = 20)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot 6: Barplot for Tumor Stage
p6 <- ggplot(data, aes(x = AJCC_PATHOLOGIC_TUMOR_STAGE)) +
  geom_bar(fill = "purple") +
  labs(title = "Tumor Stage", x = "Tumor Stage", y = "Count", size = 18) +
  theme_minimal()+
  theme(plot.title = element_text(size = 20)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Arrange all plots in a 3x3 grid
patient_data <- grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2, ncol = 3)

ggsave("patient_data.png", plot = patient_data, width = 16, height = 8)


```

## Survival Analysis

```{r, message=FALSE, warning=FALSE}
library("TCGAbiolinks")
library("survival")
library("survminer")
library("SummarizedExperiment")

data_counts_survival <- data.frame(table(data$OS_STATUS))
colnames(data_counts_survival) <- c("Status", "Count")
data_counts_survival$Percentage <- round((data_counts_survival$Count / sum(data_counts_survival$Count)) * 100, 1)

p7 <- ggplot(data_counts_survival, aes(x = "", y = Count, fill = Status)) +
  geom_bar(stat = "identity", width = 1) +  # Create bars (used for pie chart)
  coord_polar(theta = "y") +  # Convert to pie chart
  labs(title = "Overal Survival Status", fill = "Status", ) +
  theme_void() +  # Remove gridlines and axes
  theme(plot.title = element_text(size = 28),
        legend.text = element_text(size = 25),               # Increase legend text size
    legend.title = element_text(size = 28)) + 
  geom_text(aes(label = paste(Count, "(", Percentage, "%)", sep = "")), 
            position = position_stack(vjust = 0.5), size = 10) 


library(dbplyr)
data_counts_free <- data.frame(table(data$DFS_STATUS))
colnames(data_counts_free) <- c("Status", "Count")
data_counts_free$Percentage <- round((data_counts_free$Count / sum(data_counts_free$Count)) * 100, 1)

data_counts_free <- data_counts_free %>% filter(Status != "")

p8 <- ggplot(data_counts_free, aes(x = "", y = Count, fill = Status)) +
  geom_bar(stat = "identity", width = 1) +  # Create bars (used for pie chart)
  coord_polar(theta = "y") +  # Convert to pie chart
  labs(title = "Living Status", fill = "Status") +
  theme_void() +  # Remove gridlines and axes
  theme(plot.title = element_text(size = 28),
        legend.text = element_text(size = 25),               # Increase legend text size
    legend.title = element_text(size = 28)) + 
  geom_text(aes(label = paste(Count, "(", Percentage, "%)", sep = "")), 
            position = position_stack(vjust = 0.5),size = 10) 

Status_Plot <- grid.arrange(p7, p8, nrow = 1, ncol = 2)

ggsave("Status_Plot.png", plot = Status_Plot, width = 16, height = 6)
```

```{r, message=FALSE, warning=FALSE}
clin_df = data[,
                    c("PATIENT_ID",
                      "OS_STATUS",
                      "OS_MONTHS",
                      "DAYS_LAST_FOLLOWUP",
                      "AGE",
                      "SEX",
                      "AJCC_PATHOLOGIC_TUMOR_STAGE", 
                      "SUBTYPE", 
                      "RACE", 
                      "PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT",
                      "GENETIC_ANCESTRY_LABEL",
                      "RADIATION_THERAPY" ,
                      "PERSON_NEOPLASM_CANCER_STATUS",
                      "ETHNICITY",
                      "HISTORY_NEOADJUVANT_TRTYN",
                      "NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT")]

clin_df$deceased = clin_df$OS_STATUS == "1:DECEASED"
```

```{r}
clin_df[which(clin_df$AJCC_PATHOLOGIC_TUMOR_STAGE == "N/A"), "AJCC_PATHOLOGIC_TUMOR_STAGE"] = NA
clin_df$AJCC_PATHOLOGIC_TUMOR_STAGE = gsub("[ABC]$", "", clin_df$AJCC_PATHOLOGIC_TUMOR_STAGE)

# Turmor Stage Survival
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$AJCC_PATHOLOGIC_TUMOR_STAGE
fit = survfit(Surv(OS_MONTHS, deceased) ~ AJCC_PATHOLOGIC_TUMOR_STAGE, data=clin_df)

stage_survival_plot <- ggsurvplot(fit, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35, legend.labs = c("Stage: I", "Stage: II", "Stage: III", "Stage: IV", "Stage: X"), title = "Survival Anlaysis of Cancer Stage", xlab = "Time (Months)")

stage_survival_plot$plot <- stage_survival_plot$plot +
  theme(
    plot.title = element_text(size = 23),  # Title size
    legend.text = element_text(size = 15),               # Legend text size
    legend.title = element_text(size = 15)               # Legend title size
  )
stage_survival_plot$table <- stage_survival_plot$table +
  theme(legend.position = "none")

combined_plot <- grid.arrange(stage_survival_plot$plot, stage_survival_plot$table, ncol = 1, heights = c(2, 1))

ggsave("stage_survival_plot.png", combined_plot, width = 14, height = 6)
```

```{r}
# Race Survival 
clin_df[which(clin_df$RACE == "N/A"), "RACE"] = NA
clin_df[which(clin_df$RACE == "Native"), "RACE"] = NA

Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$RACE
fit_race = survfit(Surv(OS_MONTHS, deceased) ~ RACE, data=clin_df)
ggsurvplot(fit_race, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35,title = "Survival Analysis of Race", xlab = "Time (Months)")
```

```{r}
# Cancer status
table(data$AGE)
clin_df$age_group <- cut(clin_df$AGE,
                         breaks = c(20, 40, 60, 80, Inf),  # Define breakpoints
                         labels = c("20-40", "40-60", "60-80", "80+"),  # Define labels
                         right = TRUE)  # Include upper bound in each range
table(clin_df$age_group) 
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$age_group
fit_age = survfit(Surv(OS_MONTHS, deceased) ~ age_group, data=clin_df)
ggsurvplot(fit_age, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35,legend.labs = c("20-40", "40-60", "60-80", "80+"), title = "Survival Anlysis of Age", xlab = "Time (Months)")


```

```{r}
# Subtype Survival
clin_df[which(clin_df$SUBTYPE == "N/A"), "SUBTYPE"] = NA
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$SUBTYPE
fit_subtype = survfit(Surv(OS_MONTHS, deceased) ~ SUBTYPE, data=clin_df)

subtype_survival_plot <- ggsurvplot(fit_subtype, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35, legend.labs = c("BRCA_Basal", "BRCA_Her2", "BRCA_LumA", "BRCA_LumB", "BRCA_Normal"), title= "Survival Analysis of Cancer Subtype", xlab = "Time (Months)")

subtype_survival_plot$plot <- subtype_survival_plot$plot +
  theme(
    plot.title = element_text(size = 23),  # Title size
    legend.text = element_text(size = 15),               # Legend text size
    legend.title = element_text(size = 15)               # Legend title size
  )
subtype_survival_plot$table <- subtype_survival_plot$table +
  theme(legend.position = "none")

combined_plot <- grid.arrange(subtype_survival_plot$plot, subtype_survival_plot$table, ncol = 1, heights = c(2, 1))

ggsave("subtype_survival_plot.png", combined_plot, width = 14, height = 6)
```

```{r}
# Radiation Surviavl 
table(clin_df$RADIATION_THERAPY)
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$RADIATION_THERAPY
fit_rad = survfit(Surv(OS_MONTHS, deceased) ~ RADIATION_THERAPY, data=clin_df)
ggsurvplot(fit_rad, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35, title = "Survival analysis of Radiation Treatment", xlab = "Time (Months)")
```

```{r}
# Cancer status
table(data$PERSON_NEOPLASM_CANCER_STATUS)
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$PERSON_NEOPLASM_CANCER_STATUS
fit_status = survfit(Surv(OS_MONTHS, deceased) ~ PERSON_NEOPLASM_CANCER_STATUS, data=clin_df)
ggsurvplot(fit_status, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35,legend.labs = c("Tumor Free", "With Tumor"), title = "Survival Analysis of Cancer Status", xlab = "Time (Months)")
```

```{r}
#new tumor
table(data$NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT)
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ data$NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT
fit_new = survfit(Surv(OS_MONTHS, deceased) ~ NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT, data=clin_df)
ggsurvplot(fit_new, data=clin_df, pval=T, risk.table=T, risk.table.col="strata", risk.table.height=0.35,legend.labs = c("No new tumor", "New Tumor after treatment"), title = "Survival Analysis of Post Treatment Status", xlab = "Time (Months)")
```

```{r}
#combinations
Surv(clin_df$OS_MONTHS, clin_df$deceased) ~ clin_df$PERSON_NEOPLASM_CANCER_STATUS + clin_df$SUBTYPE
fit_comb = survfit(Surv(OS_MONTHS, deceased) ~ clin_df$PERSON_NEOPLASM_CANCER_STATUS + clin_df$SUBTYPE, data=clin_df)
ggsurvplot(fit_comb, data=clin_df, pval=T, legend = "bottom",legend.labs = c("TF: Basal", "TF: Her2", "TF: LumA","TF: LumB","TF: Normal","WT: Basal", "WT: Her2", "WT: LumA","WT: LumB","WT: Normal"), title = "Comparing subtype to tumor free(TF) and with tumor (WT)", xlab = "Time (Months)")
```

